### ISSUE TITLE
Makes xfce4-pulseaudio-plugin crash

### ISSUE THREAD

**Issue by haarp** [ryanswilson59/pianobar-mediaplayer2#1]
Hello,

I'd love to add mpris2 to pianobar! However it tends to make the panel plugin that handles mpris2 (xfce4-pulseaudio-plugin) crash for me as long as pianobar-mediaplayer2 is running. Here's the only output I get from the panel:

```GLib:ERROR:../glib-2.60.7/glib/gvariant-serialiser.c:1367:g_variant_serialised_n_children: code should not be reached```

It's possibly also a bug in the panel plugin, but since it works with other media players, I can't say for sure.

Any ideas? Thanks!

**Comment by haarp** [comment]
Relevant code from glib for my version: https://github.com/GNOME/glib/blob/2.60.7/glib/gvariant-serialiser.c#L1367

**Comment by ryanswilson59** [comment]
Just a quick question, have you been able to get it to work at all. And does this issue happen after starting pianobar-mediaplayer2 multiple times in a session? Could you check if there are multiple instances of the process running in something like htop?

Also if you never have been able to get it to run, that would also be helpful.
Ill see if i can recreate the issue.

**Comment by haarp** [comment]
Thanks for your reply!

No I haven't gotten it to work at all. The panel plugin crashes instantly after starting the script. I'm certain there's no other instance running either.

**Comment by ryanswilson59** [comment]
Ok I was able to recreate the issue.

**Comment by ryanswilson59** [comment]
<s>I pushed some changes to master that I believe work. I have tested it in a VM running xubuntu. I do think there might be a bug in the xfce4 panel plugin. Media players can support a playername.instance1234 format, but do not need too. The crash was fixed when I added this. 

Let me know if this works for you now, and if a does we can close the issue.  </s>

Never mind, I ran it a few times and it didn't crash, and now it is crashing again.

**Comment by ryanswilson59** [comment]
I believe the issue was I did not set a default value for the metadata before pianobar got started. 

The application should work now, let me know if it works.

**Comment by haarp** [comment]
Thanks!

Indeed, it does not crash the panel plugin anymore. Unfortunately, it doesn't add pianobar to the list of media players either.

The panel plugin shows no logs. pianobar-mediaplayer2 is running and logs e.g.:

```
b'songstart\n'
b'artist=Dance With the Dead\ntitle=Her Ghost\nalbum=The Shape\ncoverArt=http://cont-2.p-cdn.us/images/public/int/4/4/9/7/800077944_500W_500H.jpg\nstationName=QuickMix\nsongStationName=Synthwave\npRet=1\npRetStr=Everything is fine :)\nwRet=0\nwRetStr=No error\nsongDuration=289\nsongPlayed=0\nrating=1\ndetailUrl=http://www.pandora.com/dance-with-dead/shape/her-ghost/TRrZwxm9zX2bV34?dc=1777&ad=1:0:1:12345::0:0:0:0:532:069:NY:36093:0:0:0:0:0:1\nstationCount=5\nstation0=Heavy Metal\nstation1=Synthwave\nstation2=Thumbprint Radio\nstation3=Viking\nstation4=QuickMix\n'
b'stationfetchplaylist\n'
...
```

This could be a bug in the panel plugin too, not sure. But it works well with mpv + [mpv-mpris](https://github.com/hoyon/mpv-mpris).

**Comment by haarp** [comment]
Since the media shows up nicely in `playerctl` and xfce4-pulseaudio-plugin doesn't crash anymore, I'll close this.

The fact that pianobar doesn't show up as a player in xfce4-pulseaudio-plugin is very likely a bug in the latter. See https://gitlab.xfce.org/panel-plugins/xfce4-pulseaudio-plugin/-/issues/39

Cheers!
